const Personas = {
  Personas: [
    {
      id: 1,
      Nombre: "Juan",
      Apellido: "Acevedo",
      Direccion: "cr 34 45 54",
      Puesto: 10,
      Lugar: "Universidad Manizales",
      Ciudad: "Manizales",
      Departamento: "Caldas",
    },
    {
      id: 2,
      Nombre: "María",
      Apellido: "Gómez",
      Direccion: "cl 23 12 67",
      Puesto: 5,
      Lugar: "Colegio La Esperanza",
      Ciudad: "Medellín",
      Departamento: "Antioquia",
    },
    {
      id: 3,
      Nombre: "Carlos",
      Apellido: "Pérez",
      Direccion: "av 7 14 45",
      Puesto: 12,
      Lugar: "Escuela Simón Bolívar",
      Ciudad: "Cali",
      Departamento: "Valle del Cauca",
    },
    {
      id: 4,
      Nombre: "Ana",
      Apellido: "Rodriguez",
      Direccion: "av 6 23 88",
      Puesto: 8,
      Lugar: "Instituto Técnico",
      Ciudad: "Manizales",
      Departamento: "Caldas",
    },
    {
      id: 5,
      Nombre: "Luis",
      Apellido: "Ramirez",
      Direccion: "cr 45 34 12",
      Puesto: 4,
      Lugar: "Universidad Nacional",
      Ciudad: "Medellín",
      Departamento: "Antioquia",
    },
    {
      id: 6,
      Nombre: "Paola",
      Apellido: "Torres",
      Direccion: "cl 56 12 34",
      Puesto: 9,
      Lugar: "Colegio Los Alamos",
      Ciudad: "Cali",
      Departamento: "Valle del Cauca",
    },
    {
      id: 7,
      Nombre: "Sergio",
      Apellido: "López",
      Direccion: "av 5 16 45",
      Puesto: 11,
      Lugar: "Instituto de Ciencias",
      Ciudad: "Manizales",
      Departamento: "Caldas",
    },
    {
      id: 8,
      Nombre: "Tatiana",
      Apellido: "Jiménez",
      Direccion: "cr 34 56 12",
      Puesto: 6,
      Lugar: "Escuela de Artes",
      Ciudad: "Medellín",
      Departamento: "Antioquia",
    },
    {
      id: 9,
      Nombre: "David",
      Apellido: "Martínez",
      Direccion: "cl 12 34 56",
      Puesto: 7,
      Lugar: "Colegio Técnico",
      Ciudad: "Cali",
      Departamento: "Valle del Cauca",
    },
    {
      id: 10,
      Nombre: "Juliana",
      Apellido: "Herrera",
      Direccion: "av 78 90 12",
      Puesto: 10,
      Lugar: "Universidad de Caldas",
      Ciudad: "Manizales",
      Departamento: "Caldas",
    },
  ],
  Zona_Votacion: [
    {
      Id: 1,
      Direccion: "cr 12 13 465",
      Numero_Pto: 20,
      Lugar: "Universidad Santiago",
      Ciudad: "Cali",
      Departamento: "Valle del cauca",
    },
    {
      Id: 2,
      Direccion: "av 34 56 78",
      Numero_Pto: 30,
      Lugar: "Politécnico Jaime Isaza",
      Ciudad: "Medellín",
      Departamento: "Antioquia",
    },
    {
      Id: 3,
      Direccion: "cl 23 45 67",
      Numero_Pto: 15,
      Lugar: "Universidad de Manizales",
      Ciudad: "Manizales",
      Departamento: "Caldas",
    },
    {
      Id: 4,
      Direccion: "cr 67 89 01",
      Numero_Pto: 25,
      Lugar: "Colegio Comfenalco",
      Ciudad: "Cali",
      Departamento: "Valle del cauca",
    },
    {
      Id: 5,
      Direccion: "av 12 34 56",
      Numero_Pto: 20,
      Lugar: "Instituto Tecnológico Metropolitano",
      Ciudad: "Medellín",
      Departamento: "Antioquia",
    },
    {
      Id: 6,
      Direccion: "cl 78 90 12",
      Numero_Pto: 10,
      Lugar: "Colegio San Bartolomé",
      Ciudad: "Manizales",
      Departamento: "Caldas",
    },
    {
      Id: 7,
      Direccion: "cr 56 78 90",
      Numero_Pto: 15,
      Lugar: "Universidad Autónoma",
      Ciudad: "Cali",
      Departamento: "Valle del cauca",
    },
    {
      Id: 8,
      Direccion: "av 90 12 34",
      Numero_Pto: 25,
      Lugar: "Escuela de Ingeniería de Antioquia",
      Ciudad: "Medellín",
      Departamento: "Antioquia",
    },
    {
      Id: 9,
      Direccion: "cl 34 56 78",
      Numero_Pto: 20,
      Lugar: "Instituto Tecnológico de Caldas",
      Ciudad: "Manizales",
      Departamento: "Caldas",
    },
    {
      Id: 10,
      Direccion: "cr 12 34 56",
      Numero_Pto: 15,
      Lugar: "Colegio Santa María",
      Ciudad: "Cali",
      Departamento: "Valle del cauca",
    },
  ],
};

module.exports = Personas;
